credentials:
  usernames:
    jsmith:
      email: jsmith@company.com
      name: John Smith
      password: abc123
    rdoe:
      email: rdoe@company.com
      name: Jane Doe
      password: abc123
    aarav:
      email: aarav.sharma@company.com
      name: Aarav Sharma
      password: abc123

cookie:
  expiry_days: 30
  key: enterprise_security_signature_key
  name: enterprise_ai_cookie

preauthorized:
  emails: []